version: '3.8'

services:
  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # Backend development
  backend:
    build:
      context: .
      target: backend-builder
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    env_file:
      - .env.development
    command: npm run dev
    depends_on:
      - redis

  # Frontend development
  frontend:
    build:
      context: .
      target: frontend-builder
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_WEBSOCKET_URL=ws://localhost:3000
    command: npm start
    stdin_open: true
    tty: true

volumes:
  redis_dev_data:
    driver: local